# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFQGpXz9MJntfACxJzd08YNbILifddyL

**IMPORTING PACKAGES**
"""

!pip install openai chromadb python-dotenv

!pip install groq python-dotenv

"""**loading packages**"""

import os
import json
from openai import OpenAI
from dotenv import load_dotenv
from groq import Groq
import chromadb

from google.colab import userdata
groqapikey=userdata.get('GROQ_AYPI_KE')
print(groqapikey[:10])

client = Groq(api_key=groqapikey)
print("GROQ client created succresfully!!")

"""# communicating to the Groq Api:"""

response = client.chat.completions.create(
     model='llama-3.3-70b-versatile',
     messages=[
         {'role':'system','content':'you are a helpful assistant'},
         {'role':'user','content':'tell me about rgukt'},

     ]
)
print(response.choices[0].message.content)

response.model_dump_json()

"""# Loading and Chunking the data from the documents"""

with open('/content/.config/_data/company_hr_policy.txt','r') as f:
  hr_document=f.read()
print(hr_document)

with open('/content/.config/_data/company_hr_policy.txt','r') as f:
  hr_document=f.read()

with open('/content/.config/_data/engineering_standards.txt','r') as f:
  engineering_document=f.read()

with open('/content/.config/_data/onboarding_guide.txt','r') as f:
  onboarding=f.read()


with open('/content/.config/_data/product_knowledge_base.txt','r') as f:
  product=f.read()


with open('/content/.config/_data/security_policy.txt','r') as f:
  security=f.read()

print(f"HR_POLICY DOCUMENT LENGTH:{len(hr_document)}")

"""**Chunking Strategy**"""

def chunk_document(text,source_name):
  #split on double new lines
  paragraph=text.strip().split('\n\n')

  chunks=[]

  for para in paragraph:
    para=para.strip()
    if len(para)<50:
      continue
    if para.startswith('==='):
      continue
    chunks.append({'text':para,'source':source_name})

  return chunks

hr_chunks=chunk_document(hr_document,'HR POLICY')
engineering_chunks=chunk_document(engineering_document,'ENGINEERING POLICY')
onboarding_chunks=chunk_document(onboarding,'ONBOARDING GUIDE')
product_chunks=chunk_document(product,'PRODUCT KNOWLEDGE BASE')
security_chunks=chunk_document(security,'SECURITY POLICY')

print(len(hr_chunks))
print(len(engineering_chunks))
print(len(onboarding_chunks))
print(len(product_chunks))
print(len(security_chunks))

all_chunks=hr_chunks+engineering_chunks+onboarding_chunks+product_chunks+security_chunks
print(len(all_chunks))

"""# storing chunks with chromadb"""

chroma_client=chromadb.Client()
collection=chroma_client.create_collection(name='company_docs')

documents=[]
ids=[]
metadatas=[]
for i,chunk in enumerate(all_chunks):
  documents.append(chunk['text'])
  ids.append(f'chunk_{i}')
  metadatas.append({'source': chunk['source']})
print(documents[110])
print(ids[110])
print(metadatas[110])

"""# adding the vectors to the chromaDB"""

collection.add(
    documents=documents,
    metadatas=metadatas,
    ids=ids
)

"""# using [ all-MiniLM-L6-v2 ] model to convert the chunks (sentences)into the embeddings"""

from sentence_transformers import SentenceTransformer
model=SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

sentence1=''' i love biryani and chicken '''
sentence2=''' i love eating flavoured rice with chicken '''
sentence3=''' i am doing work from home '''

embedding1=model.encode(sentence1)
embedding2=model.encode(sentence2)
embedding3=model.encode(sentence3)

"""# using cosine similarity to check the similarity between two embeddings"""

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

similarity1=cosine_similarity([embedding1],[embedding2])
similarity2=cosine_similarity([embedding1],[embedding3])
print(similarity1)
print(similarity2)
#

"""# Building Retrievel Pipeline"""

def retrieve(question, n_results=3):
  results=collection.query(
      query_texts=[question],
      n_results=n_results

  )
  return results['documents'][0],results['metadatas'][0]

chunks,sources=retrieve("what is work form home policy?",3)

for i in range(len(chunks)):
  print(f'--chunks{i+1}--')
  print(f"source:{sources[i]}")
  print(f"Text:{chunks[i]}")
  print()

"""**RETRIVAL**"""

def ask_rag(question,n_results=3,verbose=True):
  chunks,sources=retrieve(question,n_results)

  if verbose:
    print(f"\n{'='*60}")
    print(f"Question: {question}")
    print(f"\n{'='*60}")
    print(f"Retrived {len(chunks)} chunks:")
    for i,(chunk,source) in enumerate(zip(chunks,sources)):
      print(f"  [{source['source']}]  {chunk[:80]}....")
    print(f"{'_'*60}")

  context='\n\n'.join(chunks)

  messages=[{

            "role":"system",
            "content" :(
                "you are a helpful assistance that answers question based only on the provided context"
                "If the content does not contain information to answer the question,"
                "say i dont have enough information or information to answer this question"
                "do not make up information or assume anything. strictly answer only form the provided context"
                 )
            },
            {
                "role":"user",
                "content":f"question:{question} context:{context}"
            }

  ]

  response = client.chat.completions.create(
     model='llama-3.3-70b-versatile',
     messages=messages,
     temperature=0.2 #Low temprature for actual answers not for creativity
  )
  answer=response.choices[0].message.content

  if verbose:
    print(f'Answer:{answer}')
    print(f"{'='*60}")
  return answer

print("Rag pipeline is built")

"""**TEST RAG PIPELIE**"""

ask_rag("what is the work form home policy")

"""# Test the Rag pipeline"""

ask_rag("what is the work form policy")

ask_rag("how many days of annual leave do employees get")

ask_rag("what is the capital of france")